### Get User
GET {{url}}/api/v1/auth/me
Authorization: Bearer {{token}}

### Get All Users
GET {{url}}/api/v1/auth/users
Authorization: Bearer {{token}}


### Update User
PUT {{url}}/api/v1/auth/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "category": 1,
    "address": "325 Swingline Ln, Milton GA 30004"
}

### Login User
POST {{url}}/api/v1/auth/login
Content-Type: application/json

{
	"email": "milton@live.com",
	"password": "123456"
}


### Register User 1
POST {{url}}/api/v1/auth/register
Content-Type: application/json

{
    "id": "a741d85b-d6db-4b3b-b871-79acf9ef52cb",
	"firstName": "Milton",
	"lastName": "Chandradas",
	"email": "milton@live.com",
	"password": "123456",
	"address": "325 Swingline Ln, Milton GA 30004"
}

### Register User 2
POST {{url}}/api/v1/auth/register
Content-Type: application/json

{
    "id": "46b01037-6029-449d-b48f-8d8f9308c192",
	"firstName": "Christoph",
	"lastName": "Christophersen",
	"email": "christoph@live.com",
	"password": "123456",
	"address": "8000 Avalon Blvd, Alpharetta GA 30004"
}

### Register User 3
POST {{url}}/api/v1/auth/register
Content-Type: application/json

{
    "id": "8333b764-8252-4e16-ab4a-34163af0d61f",
	"firstName": "Evan",
	"lastName": "Schiele",
	"email": "evan@live.com",
	"password": "123456",
	"address": "2950 Holcomb Bridge Rd, Alpharetta, GA 30022"
}


### Register User 4
POST {{url}}/api/v1/auth/register
Content-Type: application/json

{
    "id": "a20f3ffb-09a1-48aa-a9f6-7183584944d7",
	"firstName": "Rachel",
	"lastName": "Clemens",
	"email": "rachel@live.com",
	"password": "123456",
	"address": "5210 Windward Pkwy, Alpharetta, GA 30004"
}


### Register User 5
POST {{url}}/api/v1/auth/register
Content-Type: application/json

{
    "id": "2eace2bb-4871-4696-875d-9484f7291d75",
	"firstName": "Gurudatt",
	"lastName": "Kashyapp",
	"email": "gurudatt@live.com",
	"password": "123456",
	"address": "4025 North Point Pkwy, Alpharetta, GA 30022"
}


### Register User 6
POST {{url}}/api/v1/auth/register
Content-Type: application/json

{
    "id": "1100b07f-e203-43e5-9f0d-93f2e1a28cfb",
	"firstName": "Sundeep",
	"lastName": "Shah",
	"email": "sundeep@live.com",
	"password": "123456",
	"address": "5350 McGinnis Ferry Rd, Alpharetta, GA 30005"
}


### Register User 7
POST {{url}}/api/v1/auth/register
Content-Type: application/json

{
    "id": "8a1935d7-26e6-4e36-94ff-765d0f2304f1",
	"firstName": "Mike",
	"lastName": "Siebert",
	"email": "mike@live.com",
	"password": "123456",
	"address": "10975 State Bridge Rd, Alpharetta, GA 30022"
}


### Register User 8
POST {{url}}/api/v1/auth/register
Content-Type: application/json

{
    "id": "c518be09-08a7-41bb-a32d-690ed6e5046a",
	"firstName": "Harish",
	"lastName": "Kumara",
	"email": "harish@live.com",
	"password": "123456",
	"address": "12350 Arnold Mill Rd, Alpharetta, GA 30004"
}

### Register User 9
POST {{url}}/api/v1/auth/register
Content-Type: application/json

{
    "id": "11539e8c-a4df-4337-8b9c-5c0474c854b4",
	"firstName": "Jean",
	"lastName": "Lauzon",
	"email": "jean@live.com",
	"password": "123456",
	"address": "591 Holcomb Bridge Rd, Roswell, GA 30076"
}


### Register User 10
POST {{url}}/api/v1/auth/register
Content-Type: application/json

{
    "id": "3a48c513-1a33-4509-bc8b-4cecaa9eb143",
	"firstName": "Antonia",
	"lastName": "Zorn",
	"email": "antonia@live.com",
	"password": "123456",
	"address": "5750 GA-9 N, Alpharetta, GA 30004"
}