### GET All Products
GET {{url}}/api/v1/products


### POST Product
POST {{url}}/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMwNTA5OTBjLTIxNjctNDk2ZC05ZjM5LWM5MTFhYzk2MGFmMyIsImZpcnN0TmFtZSI6Ik1pbHRvbiIsImxhc3ROYW1lIjoiQ2hhbmRyYWRhcyIsImVtYWlsIjoibWlsdG9uQGxpdmUuY29tIiwiaWF0IjoxNTkzODYwNDc3LCJleHAiOjE1OTY0NTI0Nzd9.gPid0Cz96BR9V2MGPFWDjMVTvlUYcvJWp8QAAz7x2QE
Content-Type: application/json

{
	"name": "27 inch monitor",
	"description": "Brand new Samsung 27 inch 4k monitor",
	"price": "free - but you would have to come and pick it up",
	"comments": "I am handicapped and elderly.  And it would be great if you can help me with groceries in return...  Thanks !"
}


