### GET All Services
GET {{url}}/api/v1/services

### GET All Services for user
GET {{url}}/api/v1/services?id=72f46ac0-6a48-4a88-88e0-9bc618705972


### POST Service
POST {{url}}/api/v1/services
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImMwNTA5OTBjLTIxNjctNDk2ZC05ZjM5LWM5MTFhYzk2MGFmMyIsImZpcnN0TmFtZSI6Ik1pbHRvbiIsImxhc3ROYW1lIjoiQ2hhbmRyYWRhcyIsImVtYWlsIjoibWlsdG9uQGxpdmUuY29tIiwiaWF0IjoxNTkzODYwNDc3LCJleHAiOjE1OTY0NTI0Nzd9.gPid0Cz96BR9V2MGPFWDjMVTvlUYcvJWp8QAAz7x2QE
Content-Type: application/json

{
	"name": "27 inch monitor",
	"description": "Brand new Samsung 27 inch 4k monitor",
	"price": "free - but you would have to come and pick it up",
	"comments": "I am handicapped and elderly.  And it would be great if you can help me with groceries in return...  Thanks !"
}


### PUT Service
PUT {{url}}/api/v1/services/b3776886-39f8-4b96-aa50-a76e83ad1cf4
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "providerId": "11539e8c-a4df-4337-8b9c-5c0474c854b4",
    "beneficiaryId": "c518be09-08a7-41bb-a32d-690ed6e5046a",
    "startDate": "2020-08-06T00:00:00.000Z",
    "endDate": "2020-08-06T00:00:00.000Z",
    "initiatedBy": "beneficiary"
}

